package se.blacklemon.model.Classification;

public enum Classification {
    ACTION, BIOGRAPHIC, CLASSIC, COMIC, COOKBOOK, ESSAY, FANTASY, FICTION, HISTORY, HORROR, POETRY, ROMANCE, SCIENCE, STORY, SUSPENSE, TRUE_CRIME;
}
